apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: minecraft
data:
  # Mengubah isi appConfig di values.yaml menjadi file text yaml biasa
  application-external.yaml: |
    {{- toYaml .Values.appConfig | nindent 4 }}
