apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            # Menginstruksikan Spring Boot untuk memilih file config di dalam JAR
            - name: NEXT_PUBLIC_API_URL
              value: "{{ .Values.publicApiUrl }}"
            - name: NEXTAUTH_SECRET
              value: "{{ .Values.nextAuthSecret }}"
            - name: BETTER_AUTH_SECRET
              value: "{{ .Values.betterAuthSecret }}"
