apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-web
  namespace: minecraft
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # Minta cert-manager buatkan sertifikat otomatis
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - craft.shemhazai.my.id
      secretName: shemhazaicraft-tls
  rules:
    - host: craft.shemhazai.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shemhazaicraft-web
                port:
                  number: 3000