apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: minecraft
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000                 # <--- Ganti "http" langsung ke angka 3000 (atau name: http jika deployment sudah di-update)
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}           # <--- Hapus baris 'release: ...', cukup 'app' saja